### ISSUE TITLE
Provider  - send coins - cancel button doesn't work

### ISSUE THREAD

**Issue by dangershony** [block-core/blockcore-wallet#322]
![image](https://user-images.githubusercontent.com/7487930/210641059-9b777257-d4bd-42db-8b95-061451a2a60d.png)

I clicked cancel twice and still got a trx sent out

![image](https://user-images.githubusercontent.com/7487930/210641163-8214fc3f-fcec-4cc8-9d43-bafe27a87904.png)

**Comment by sondreb** [comment]
The confirm dialog was shown always, but you have to test and verify that it actually sent if you clicked Cancel or clicked away on this dialog, because I was not able to reproduce that. Cancel of this dialog should just go back to the other view, not close the whole window.

The confirmation is no longer shown if you click cancel on the first cancel button.
